### ISSUE TITLE
file/directory renaming confusion

### ISSUE THREAD

**Issue by powersjohnp** [MotivatedMemoryLab/biacpype#3]
I was not aware that all the files and directories would initially be named using the wrong convention (BIAC_IDs and dates), and would all be corrected/renamed at the very end of the conversion process. Since the full conversion of my data set takes a whole day, I was stopping the process before completion to try to troubleshoot. Other users may also assume the pipeline is not working correctly unless this is clarified in the manual or the naming process is changed to apply the correct names from the beginning.

**Comment by lpjiang97** [comment]
edits: see d82a00e 
---
Sorry for the late reply -- my Duke email was deactivated before so I wasn't getting email notifications open an issue is opened. 

You are correct -- the reason was because the pipeline wraps a previously developed script `bxh2bids`, and the naming from that part was incorrect. The `clean_names` module does exactly the correct name conversions. I hope the naming after the pipeline finishes will be correct, *if not, let me know.*

Thanks for raising this issue. I will add a note in the manual. In the future, the goal is to rewrite some parts of `bxh2bids`.
